spring.application.name=investTracker
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
gemini.api.key=${GEMINI_API_KEY}
gemini.model=gemini-2.5-flash
finhub.api.key=${FINHUB_API_KEY}
jwt.secret=${JWT_SECRET:ToJestBardzoTajnyKluczDoNaszejAplikacjiZainwestujWBitcoina12345!}